# 不蒜子计数
busuanzi:
  site: true
  page: true
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# 文末结束语
passage_end_tag:
  enabled: true
  text: --- 本文结束 <i class="fa fa-heartbeat"></i> The End ---

# Google Adsense广告代码
google_adsense:
  enabled: true
  footer: ../_adsense/footer.ejs
  sidebar: ../_adsense/sidebar.ejs
  banner: ../_adsense/banner.ejs


# 使用Mathjax渲染数学公式
mathjax:
  enabled: true

# 自动生成的摘要长度
# 建议文章中手动使用 <!--more--> 效果更佳
excerpt_length: 150

# 主题颜色
theme_color:
  primary: blue-grey #teal
  accent: blue

# 菜单
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || bookmark
  categories: /categories/ || folder
  archives: /archives/ || archive
  抽象话转换器: /NMSL/ || attach_money
  sitemap: /sitemap.xml || map
  #resources: /resources || download

###
avatar: /images/avatar.jpg
favicon: /images/favicon.png

# 页脚
footer:
  since: 2015
  footer_text:
  license:

# 页面    
page:
  tag_count: true

# 评论
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  gitalk_sid_type:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:

# 社交链接
social:
  GitHub: https://github.com/kb1000fx || fab fa-github
  Steam: https://steamcommunity.com/profiles/76561198346798163 || fab fa-steam
  E-Mail: mailto:kb1000fx@gmail.com || fas fa-envelope
  #Weibo: https://weibo.com/yourname || weibo
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype


email:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

search:
  placeholder: 请输入关键字
  path: /search.xml
  use: plugin

